### PR TITLE
Update and fix version check

### PR DESCRIPTION
**Pull request by Anthchirp**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

A duplicate key in the recipe cause the conda-forge automated update check to fail, so I removed that.

### CODE REVIEW

**Comment by Anthchirp** [comment]
@conda-forge-admin, please rerender

**Comment by cbrueffer** [comment]
@conda-forge-admin please rerender

**Comment by dbast** [comment]
@Anthchirp thx

**Comment by cbrueffer** [comment]
Indeed, thanks @Anthchirp ! Not sure why the bot didn't pick up the update.

**Comment by Anthchirp** [comment]
The bot parses the recipe differently to conda-build and if it encounters any issues it will err on the side of caution and not create a pull request. Here the duplicate yaml key was enough to stop it from picking up any updates.

The same issue also affects 
- [x] r-ggalluvial, 
- [x] r-goric, 
- [x] r-fivethirtyeight, 
- [x] r-sigmajs, 
- [x] r-mosaicdata and 
- [x] r-shinyalert

I'll prepare PRs for those later today unless you want to pick them up immediately.

**Pull request merged**
